/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/arquivos/': RouteRecordInfo<'/arquivos/', '/arquivos', Record<never, never>, Record<never, never>>,
    '/arquivos/_components/ListNotes': RouteRecordInfo<'/arquivos/_components/ListNotes', '/arquivos/_components/ListNotes', Record<never, never>, Record<never, never>>,
    '/arquivos/_components/ListXmls': RouteRecordInfo<'/arquivos/_components/ListXmls', '/arquivos/_components/ListXmls', Record<never, never>, Record<never, never>>,
    '/empresas/': RouteRecordInfo<'/empresas/', '/empresas', Record<never, never>, Record<never, never>>,
    '/empresas/_components/ListEnterprises': RouteRecordInfo<'/empresas/_components/ListEnterprises', '/empresas/_components/ListEnterprises', Record<never, never>, Record<never, never>>,
  }
}
